name: publish

on:
  push:
    branches:
      - main
  pull_request:
    

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

    - name: Build the Docker image
      env:
        CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      run: |
        IMAGE_ID=ghcr.io/${{ github.actor }}/${{ matrix.name }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag ${{ matrix.name }} $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION